name: Firebase Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install Firebase Login
        run: npx firebase login:ci

      - name: Install Dependencies and Build
        run: |
          npm ci
          npm run build

      - name: Firebase Deploy
        run: |
          npx firebase use meme-talk-4adb4
          npx firebase deploy --only hosting
        env:
            FIREBASE_TOKEN: '${{ secrets.FIREBASE_TOKEN }}'
        