name: Firebase Deploy

on:
  push:
    branches:
      - master
  paths-ignore:
      - '*.md'
      - .gitignore

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies and Build
        run: npm install

      - name: Build site
        run: npm run build

      - name: Firebase Deploy
        run: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NUXTPARAEDUARDO }}'
          projectId: meme-talk-4adb4
          channelId: live
        