name: Firebase Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install Dependencies and Build
        run: |
          npm ci
          npm run build

      - name: Firebase Deploy
        run: |
          npx firebase use meme-talk-4adb4
          npx firebase deploy --token 1//0eujC7fQ5RIGeCgYIARAAGA4SNwF-L9IrEj2FyYIuDOCVY55EzX3Gt3Aoqez9tap4npa9QBrTTGo0S9Up6PxEEz-0brL0JLNOHRg --only hosting

      - name: Debug
        run: cat /home/runner/.npm/_logs/2024-02-03T12_54_50_236Z-debug-0.log
        env:
          FIREBASE_TOKEN: 1//0eujC7fQ5RIGeCgYIARAAGA4SNwF-L9IrEj2FyYIuDOCVY55EzX3Gt3Aoqez9tap4npa9QBrTTGo0S9Up6PxEEz-0brL0JLNOHRg